-- MySQL Script generated by MySQL Workbench
-- Qui 23 Jun 2016 08:53:29 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estudobanco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estudobanco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estudobanco` DEFAULT CHARACTER SET utf8 ;
USE `estudobanco` ;

-- -----------------------------------------------------
-- Table `estudobanco`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudobanco`.`usuario` (
  `id_usuario` INT NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudobanco`.`senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudobanco`.`senha` (
  `id_usuario` INT NOT NULL,
  `idsenha` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_senha_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_senha_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `estudobanco`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `estudobanco` ;

-- -----------------------------------------------------
-- Placeholder table for view `estudobanco`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudobanco`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `estudobanco`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudobanco`.`view1`;
USE `estudobanco`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
